// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiY03eXWxERBqVDFNaEspH8HAI5kR1zbA',
    appId: '1:159545416720:web:1af369f461db4503effe95',
    messagingSenderId: '159545416720',
    projectId: 'jop-dc281',
    authDomain: 'jop-dc281.firebaseapp.com',
    storageBucket: 'jop-dc281.firebasestorage.app',
    measurementId: 'G-6HGHN8778J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrz3JOzSZGlWHOc2PRdHhEhGVZBDYgL8',
    appId: '1:159545416720:android:b4ad12ded2938c44effe95',
    messagingSenderId: '159545416720',
    projectId: 'jop-dc281',
    storageBucket: 'jop-dc281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBo26TvLaEEKYps0yw8VWqmMp-lt6ugE',
    appId: '1:159545416720:ios:47c010ca6eab6921effe95',
    messagingSenderId: '159545416720',
    projectId: 'jop-dc281',
    storageBucket: 'jop-dc281.firebasestorage.app',
    iosBundleId: 'com.example.movieticket.movieTicketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBo26TvLaEEKYps0yw8VWqmMp-lt6ugE',
    appId: '1:159545416720:ios:47c010ca6eab6921effe95',
    messagingSenderId: '159545416720',
    projectId: 'jop-dc281',
    storageBucket: 'jop-dc281.firebasestorage.app',
    iosBundleId: 'com.example.movieticket.movieTicketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiY03eXWxERBqVDFNaEspH8HAI5kR1zbA',
    appId: '1:159545416720:web:32f78247a1336eb6effe95',
    messagingSenderId: '159545416720',
    projectId: 'jop-dc281',
    authDomain: 'jop-dc281.firebaseapp.com',
    storageBucket: 'jop-dc281.firebasestorage.app',
    measurementId: 'G-NTQLNCMH9D',
  );
}
